# BRBON document generator jazzy settings

copyright: Copyright 2016-2019 rien@balancingrock.nl
author: Balancingrock
module: BRBON
hide_documentation_coverage: false
xcodebuild_arguments: [-target, BRBON]
github_url: https://github.com/Balancingrock/BRBON
output: ~/Documents/Websites/swiftfire.nl/projects/brbon/reference
clean: true
theme: fullwidth
readme: README.md
documentation: docs/*.md
